# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Related | Power
description: >
  I'm a tech leader enjoying improving collaboration across multiple teams and productivity on tech works. I'm sharing useful tech productivity info in this blog. 
baseurl: "/related" # the subpath of your site, e.g. /blog
future: false

# Build settings
markdown: kramdown

collections:
  posts_kr:
    output: true
    permalink: /kr/:path:output_ext

paginate: 50
plugins:
  - jekyll-gist
  - jekyll-paginate

sass:
    style: compressed
